### ISSUE TITLE
Bug react-jsonschema-form-layout is outdated for the new  react-jsonschema-form

### ISSUE THREAD

**Issue by Dannergal** [audibene-labs/react-jsonschema-form-layout#30]
![image](https://github.com/audibene-labs/react-jsonschema-form-layout/assets/15927191/1d6ad718-f404-456a-a9b1-c73174d895d8)

ArrayField.js:614 Uncaught TypeError: Cannot read properties of undefined (reading 'object')
    at node_modules/react-jsonschema-form/lib/components/fields/ArrayField.js (ArrayField.js:614:30)
    at __require (chunk-AC2VUBZ6.js?v=53f7a059:11:50)
    at node_modules/react-jsonschema-form/lib/components/fields/index.js (index.js:7:19)
    at __require (chunk-AC2VUBZ6.js?v=53f7a059:11:50)
    at node_modules/react-jsonschema-form/lib/utils.js (utils.js:101:11)
    at __require (chunk-AC2VUBZ6.js?v=53f7a059:11:50)
    at node_modules/react-jsonschema-form/lib/components/fields/ObjectField.js (ObjectField.js:15:14)
    at __require (chunk-AC2VUBZ6.js?v=53f7a059:11:50)
    at node_modules/react-jsonschema-form-layout/es/index.js (index.js:16:21)
    at __require (chunk-AC2VUBZ6.js?v=53f7a059:11:50)

**Comment by Dannergal** [comment]
@marsch I saw you're contributor, I researched the issue and the problem is: the library work with react-jsonschema-form v1.x, I use react-jsonschema-form v5.x, so , react search 
import Form from "react-jsonschema-form";
and now the library is:
import Form from "@rjsf/core";

react-jsonschema-form-layout is outdated
